export const PAYMENT_MODELS: Record<string, string> = {
    "1": "CPA",
    "2": "CPC",
    "3": "CPM",
    "4": "Fixed",
    "5": "RevShare"
};

export const PAYMENT_TO: Record<string, string> = {
    "0": "Company Name",
    "1": "Main Contact"
};

export const CURRENCIES: Record<string, string> = {
    "1": "US Dollar",
    "3": "Euro",
    "4": "Indian Rupee"
};

export const COUNTRIES: Record<string, string> = {
    "AF": "Afghanistan",
    "AX": "Aland Islands",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BQ": "Bonaire, Saint Eustatius and Saba",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brazil",
    "IO": "British Indian Ocean Territory",
    "BN": "Brunei Darussalam",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo",
    "CD": "Congo, The Democratic Republic of the",
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": "Cote d'Ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CW": "Curacao",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Ethiopia",
    "FK": "Falkland Islands (Malvinas)",
    "FO": "Faroe Islands",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard Island and McDonald Islands",
    "VA": "Holy See (Vatican City State)",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran, Islamic Republic of",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "Korea, Democratic People's Republic of",
    "KR": "Korea, Republic of",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao People's Democratic Republic",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libyan Arab Jamahiriya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MO": "Macao",
    "MK": "Macedonia, The Former Yugoslav Republic of",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia, Federated States of",
    "MD": "Moldova, Republic of",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestinian Territory, Occupied",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "BL": "Saint Barthelemy",
    "SH": "Saint Helena",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "MF": "Saint Martin",
    "PM": "Saint Pierre and Miquelon",
    "VC": "Saint Vincent and the Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SX": "Sint Maarten",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": "South Georgia and the South Sandwich Islands",
    "SS": "South Sudan",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SJ": "Svalbard and Jan Mayen",
    "SZ": "Swaziland",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syrian Arab Republic",
    "TW": "Taiwan, Province of China",
    "TJ": "Tajikistan",
    "TZ": "Tanzania, United Republic of",
    "TH": "Thailand",
    "TL": "timor-leste",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks and Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UM": "United States Minor Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.",
    "WF": "Wallis and Futuna",
    "EH": "western sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
};

export const CATEGORIES: Record<string, string> = {
    "1": "Animals",
    "2": "Animals -> Pets",
    "3": "Animals -> Wildlife",
    "4": "Arts & Entertainment",
    "5": "Arts & Entertainment -> Amusement Parks",
    "6": "Arts & Entertainment -> Clubs & Nightlife",
    "7": "Arts & Entertainment -> Comedy",
    "8": "Arts & Entertainment -> Film & Television",
    "9": "Arts & Entertainment -> Games",
    "10": "Arts & Entertainment -> Music",
    "11": "Arts & Entertainment -> Pop Culture",
    "12": "Arts & Entertainment -> Reading",
    "13": "Arts & Entertainment -> Theater & Performing Arts",
    "14": "Arts & Entertainment -> Visual Arts",
    "15": "Autos",
    "16": "Business & Finance",
    "17": "Business & Finance -> Advertising & Marketing",
    "18": "Business & Finance -> Billing",
    "19": "Business & Finance -> Careers",
    "20": "Business & Finance -> Finance & Investing",
    "21": "Business & Finance -> Home Office",
    "22": "Business & Finance -> Insurance",
    "23": "Business & Finance -> Management & Corporate Operations",
    "24": "Business & Finance -> Marketing & PR",
    "25": "Business & Finance -> Small Business",
    "26": "Education",
    "27": "Education -> Career Advice",
    "28": "Education -> College",
    "29": "Education -> Financial Aid",
    "30": "Education -> Foreign Language",
    "31": "Education -> Home Schooling",
    "32": "Education -> Home Study Courses",
    "33": "Education -> Study Skills",
    "34": "Education -> Teaching Resources",
    "35": "Electronics & Computers",
    "36": "Electronics & Computers -> Brands",
    "37": "Electronics & Computers -> Cameras",
    "38": "Cell Phones / Mobiles",
    "39": "Electronics & Computers -> Components",
    "40": "Electronics & Computers -> Computers",
    "41": "Electronics & Computers -> Handhelds & PDAs",
    "42": "Electronics & Computers -> Internet Service Providers",
    "43": "Electronics & Computers -> Music Players",
    "44": "Electronics & Computers -> Networking & Wireless",
    "45": "Electronics & Computers -> Personal Electronics",
    "46": "Electronics & Computers -> Programming",
    "47": "Electronics & Computers -> Software",
    "48": "Electronics & Computers -> Televisions",
    "49": "Financial Products & Services",
    "50": "Financial Products & Services -> Banking",
    "51": "Financial Products & Services -> Credit Products",
    "52": "Financial Products & Services -> Financial Services",
    "53": "Financial Products & Services -> Insurance",
    "54": "Financial Products & Services -> Loans",
    "55": "Financial Products & Services -> Payroll & Payment",
    "56": "Financial Products & Services -> Retirement & Investing",
    "57": "Food & Drink",
    "58": "Food & Drink -> Baking",
    "59": "Food & Drink -> Coffee",
    "60": "Food & Drink -> Cooking",
    "61": "Food & Drink -> Cuisine Types",
    "62": "Food & Drink -> Health Food",
    "63": "Food & Drink -> Natural Foods",
    "64": "Food & Drink -> Restaurants",
    "65": "Food & Drink -> Snacks",
    "66": "Health, Beauty & Personal Care",
    "67": "Health, Beauty & Personal Care -> Body Art",
    "68": "Health, Beauty & Personal Care -> Face & Body Care",
    "69": "Health, Beauty & Personal Care -> Fitness",
    "70": "Health, Beauty & Personal Care -> Hair Care",
    "71": "Health, Beauty & Personal Care -> Health",
    "72": "Health, Beauty & Personal Care -> Nutrition",
    "73": "Hobbies",
    "74": "Hobbies -> Auto Work",
    "75": "Hobbies -> Collecting",
    "76": "Hobbies -> Handicrafts",
    "77": "Hobbies -> Music",
    "78": "Hobbies -> Photography",
    "79": "Hobbies -> Writing",
    "80": "Home & Garden",
    "81": "Home & Garden -> Gardening",
    "82": "Home & Garden -> Home Furnishings & Decorating",
    "83": "Home & Garden -> Home Improvement",
    "84": "Home & Garden -> Housewares",
    "85": "Internet & Online Activities",
    "86": "Internet & Online Activities -> Apps",
    "87": "Internet & Online Activities -> Blogs",
    "88": "Internet & Online Activities -> File Sharing & Hosting",
    "89": "Internet & Online Activities -> Games & Quizzes",
    "90": "Internet & Online Activities -> Navigation",
    "91": "Internet & Online Activities -> News",
    "92": "Internet & Online Activities -> Online Dating",
    "93": "Internet & Online Activities -> Photo Sharing",
    "94": "Internet & Online Activities -> Research",
    "95": "Internet & Online Activities -> Shopping",
    "96": "Internet & Online Activities -> Site Building",
    "97": "Internet & Online Activities -> Social Networking",
    "98": "Internet & Online Activities -> Streaming",
    "99": "Internet & Online Activities -> Video Sharing",
    "100": "Lifestyles",
    "101": "Lifestyles -> Clubs & Organizations",
    "102": "Lifestyles -> Country Club Members",
    "103": "Lifestyles -> Do It Yourselfers (DIY)",
    "104": "Lifestyles -> Gift Giving",
    "105": "Lifestyles -> Green Living",
    "106": "Lifestyles -> Healthy Living",
    "107": "Lifestyles -> Holidays & Seasonal Events",
    "108": "Lifestyles -> Home Entertaining",
    "109": "Lifestyles -> Luxury Pursuits",
    "110": "Lifestyles -> Military",
    "111": "Lifestyles -> Opinion Leaders",
    "112": "Lifestyles -> Parenting & Family",
    "113": "Lifestyles -> Rural Farming",
    "114": "Lifestyles -> Self-Improvement",
    "115": "Lifestyles -> Wedding Planning",
    "116": "Other Vehicles",
    "117": "Other Vehicles -> Aircraft",
    "118": "Other Vehicles -> Boats",
    "119": "Other Vehicles -> Golf Carts",
    "120": "Other Vehicles -> Heavy Equipment",
    "121": "Other Vehicles -> Military Vehicles",
    "122": "Other Vehicles -> Motorcycles & ATVs",
    "123": "Other Vehicles -> RVs, Campers & Trailers",
    "124": "Other Vehicles -> Snowmobiles",
    "125": "Outdoor Activities",
    "126": "Outdoor Activities -> Biking",
    "127": "Outdoor Activities -> Boating",
    "128": "Outdoor Activities -> Camping",
    "129": "Outdoor Activities -> Canoe & Kayak",
    "130": "Outdoor Activities -> Equestrian",
    "131": "Outdoor Activities -> Fishing",
    "132": "Outdoor Activities -> Golf",
    "133": "Outdoor Activities -> Hiking",
    "134": "Outdoor Activities -> Hunting",
    "135": "Outdoor Activities -> Skateboarding",
    "136": "Politics & Society",
    "137": "Politics & Society -> Charities & Non-Profits",
    "138": "Politics & Society -> Environmental Issues",
    "139": "Politics & Society -> Politics",
    "140": "Politics & Society -> World Affairs",
    "141": "Retail",
    "142": "Retail -> Art & Collectibles",
    "143": "Retail -> Automotive Parts & Accessories",
    "144": "Retail -> Babies & Kids",
    "145": "Retail -> Business & Office",
    "146": "Retail -> Cell Phones / Mobiles & Plans",
    "147": "Retail -> Clothing, Shoes & Accessories",
    "148": "Retail -> Computers",
    "149": "Retail -> Consumer Packaged Goods (CPG)",
    "150": "Retail -> Electronics",
    "151": "Retail -> Entertainment",
    "152": "Retail -> Hobbies, Games & Toys",
    "153": "Retail -> Home & Garden",
    "154": "Retail -> Shopping Predictors",
    "155": "Retail -> Sports Equipment & Outdoor Gear",
    "156": "Retail -> Video Games",
    "157": "Science & Humanities",
    "158": "Science & Humanities -> Anthropology",
    "159": "Science & Humanities -> Astronomy",
    "160": "Science & Humanities -> Biological Sciences",
    "161": "Science & Humanities -> Botany",
    "162": "Science & Humanities -> Chemistry",
    "163": "Science & Humanities -> Engineering",
    "164": "Science & Humanities -> Geology",
    "165": "Science & Humanities -> History",
    "166": "Science & Humanities -> Marine Biology & Oceanography",
    "167": "Science & Humanities -> Mathematics",
    "168": "Science & Humanities -> Meteorology & Climatology",
    "169": "Science & Humanities -> Philosophy",
    "170": "Science & Humanities -> Physics",
    "171": "Services",
    "172": "Services -> Arts & Entertainment",
    "173": "Services -> Facilities",
    "174": "Services -> Housing",
    "175": "Services -> Restaurants",
    "176": "Services -> Services",
    "177": "Shopping",
    "178": "Shopping -> Apparel & Accessories",
    "179": "Shopping -> Auctions",
    "180": "Shopping -> Bargain Hunting",
    "181": "Shopping -> Children",
    "182": "Shopping -> Coupons",
    "183": "Shopping -> Department Stores",
    "184": "Shopping -> Fashion",
    "185": "Shopping -> Impulse Buyers",
    "186": "Shopping -> Luxury Goods",
    "187": "Shopping -> Mail Order",
    "188": "Shopping -> Online Shoppers",
    "189": "Shopping -> Shopaholics",
    "190": "Sports",
    "191": "Sports -> Aerobics",
    "192": "Sports -> Boxing/Martial Arts/Wrestling",
    "193": "Sports -> Cycling",
    "194": "Sports -> Extreme Sports",
    "195": "Sports -> Golf",
    "196": "Sports -> Motor Sports",
    "197": "Sports -> Nascar",
    "198": "Sports -> Olympics & International Competitions",
    "199": "Sports -> Racquet Sports",
    "200": "Sports -> Running/Jogging",
    "201": "Sports -> Team Sports",
    "202": "Sports -> Walking",
    "203": "Sports -> Water Sports",
    "204": "Sports -> Winter Sports",
    "205": "Travel",
    "206": "Travel -> Air Travel",
    "207": "Travel -> Budget Travel",
    "208": "Travel -> Business Travel - International",
    "209": "Travel -> Business Travel - USA",
    "210": "Travel -> Car Rentals",
    "211": "Travel -> Cruises & Charters",
    "212": "Travel -> Hotels & Lodging?",
    "213": "Travel -> Personal Travel - International",
    "214": "Travel -> Personal Travel - USA",
    "215": "Travel -> Resorts",
    "216": "Travel -> Vacation Packages",
    "217": "Video Games",
    "218": "Video Games -> Games",
    "219": "Video Games -> Systems"
};

export const US_STATES: Record<string, string> = {
    "##": "None",
    "AK": "Alaska",
    "AL": "Alabama",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DC": "District of Columbia",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VA": "Virginia",
    "VT": "Vermont",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming"
};

export const TIMEZONES: Record<string, string> = {
    "": "",
    "Dateline Standard Time": "Dateline Standard Time",
    "UTC-11": "UTC-11",
    "Aleutian Standard Time": "Aleutian Standard Time",
    "Hawaiian Standard Time": "Hawaiian Standard Time",
    "Marquesas Standard Time": "Marquesas Standard Time",
    "Alaskan Standard Time": "Alaskan Standard Time",
    "UTC-09": "UTC-09",
    "Pacific Standard Time (Mexico)": "Pacific Standard Time (Mexico)",
    "UTC-08": "UTC-08",
    "Pacific Standard Time": "Pacific Standard Time",
    "US Mountain Standard Time": "US Mountain Standard Time",
    "Mountain Standard Time (Mexico)": "Mountain Standard Time (Mexico)",
    "Mountain Standard Time": "Mountain Standard Time",
    "Yukon Standard Time": "Yukon Standard Time",
    "Central America Standard Time": "Central America Standard Time",
    "Central Standard Time": "Central Standard Time",
    "Easter Island Standard Time": "Easter Island Standard Time",
    "Central Standard Time (Mexico)": "Central Standard Time (Mexico)",
    "Canada Central Standard Time": "Canada Central Standard Time",
    "SA Pacific Standard Time": "SA Pacific Standard Time",
    "Eastern Standard Time (Mexico)": "Eastern Standard Time (Mexico)",
    "Eastern Standard Time": "Eastern Standard Time",
    "Haiti Standard Time": "Haiti Standard Time",
    "Cuba Standard Time": "Cuba Standard Time",
    "US Eastern Standard Time": "US Eastern Standard Time",
    "Turks And Caicos Standard Time": "Turks and Caicos Standard Time",
    "Paraguay Standard Time": "Paraguay Standard Time",
    "Atlantic Standard Time": "Atlantic Standard Time",
    "Venezuela Standard Time": "Venezuela Standard Time",
    "Central Brazilian Standard Time": "Central Brazilian Standard Time",
    "SA Western Standard Time": "SA Western Standard Time",
    "Pacific SA Standard Time": "Pacific SA Standard Time",
    "Newfoundland Standard Time": "Newfoundland Standard Time",
    "Tocantins Standard Time": "Tocantins Standard Time",
    "E. South America Standard Time": "E. South America Standard Time",
    "SA Eastern Standard Time": "SA Eastern Standard Time",
    "Argentina Standard Time": "Argentina Standard Time",
    "Greenland Standard Time": "Greenland Standard Time",
    "Montevideo Standard Time": "Montevideo Standard Time",
    "Magallanes Standard Time": "Magallanes Standard Time",
    "Saint Pierre Standard Time": "Saint Pierre Standard Time",
    "Bahia Standard Time": "Bahia Standard Time",
    "UTC-02": "UTC-02",
    "Mid-Atlantic Standard Time": "Mid-Atlantic Standard Time",
    "Azores Standard Time": "Azores Standard Time",
    "Cape Verde Standard Time": "Cabo Verde Standard Time",
    "UTC": "Coordinated Universal Time",
    "GMT Standard Time": "GMT Standard Time",
    "Greenwich Standard Time": "Greenwich Standard Time",
    "Sao Tome Standard Time": "Sao Tome Standard Time",
    "Morocco Standard Time": "Morocco Standard Time",
    "W. Europe Standard Time": "W. Europe Standard Time",
    "Central Europe Standard Time": "Central Europe Standard Time",
    "Romance Standard Time": "Romance Standard Time",
    "Central European Standard Time": "Central European Standard Time",
    "W. Central Africa Standard Time": "W. Central Africa Standard Time",
    "GTB Standard Time": "GTB Standard Time",
    "Middle East Standard Time": "Middle East Standard Time",
    "Egypt Standard Time": "Egypt Standard Time",
    "E. Europe Standard Time": "E. Europe Standard Time",
    "Syria Standard Time": "Syria Standard Time",
    "West Bank Standard Time": "West Bank Gaza Standard Time",
    "South Africa Standard Time": "South Africa Standard Time",
    "FLE Standard Time": "FLE Standard Time",
    "Israel Standard Time": "Jerusalem Standard Time",
    "South Sudan Standard Time": "South Sudan Standard Time",
    "Kaliningrad Standard Time": "Russia TZ 1 Standard Time",
    "Sudan Standard Time": "Sudan Standard Time",
    "Libya Standard Time": "Libya Standard Time",
    "Namibia Standard Time": "Namibia Standard Time",
    "Jordan Standard Time": "Jordan Standard Time",
    "Arabic Standard Time": "Arabic Standard Time",
    "Turkey Standard Time": "Turkey Standard Time",
    "Arab Standard Time": "Arab Standard Time",
    "Belarus Standard Time": "Belarus Standard Time",
    "Russian Standard Time": "Russia TZ 2 Standard Time",
    "E. Africa Standard Time": "E. Africa Standard Time",
    "Volgograd Standard Time": "Volgograd Standard Time",
    "Iran Standard Time": "Iran Standard Time",
    "Arabian Standard Time": "Arabian Standard Time",
    "Astrakhan Standard Time": "Astrakhan Standard Time",
    "Azerbaijan Standard Time": "Azerbaijan Standard Time",
    "Russia Time Zone 3": "Russia TZ 3 Standard Time",
    "Mauritius Standard Time": "Mauritius Standard Time",
    "Saratov Standard Time": "Saratov Standard Time",
    "Georgian Standard Time": "Georgian Standard Time",
    "Caucasus Standard Time": "Caucasus Standard Time",
    "Afghanistan Standard Time": "Afghanistan Standard Time",
    "West Asia Standard Time": "West Asia Standard Time",
    "Ekaterinburg Standard Time": "Russia TZ 4 Standard Time",
    "Pakistan Standard Time": "Pakistan Standard Time",
    "Qyzylorda Standard Time": "Qyzylorda Standard Time",
    "India Standard Time": "India Standard Time",
    "Sri Lanka Standard Time": "Sri Lanka Standard Time",
    "Nepal Standard Time": "Nepal Standard Time",
    "Central Asia Standard Time": "Central Asia Standard Time",
    "Bangladesh Standard Time": "Bangladesh Standard Time",
    "Omsk Standard Time": "Omsk Standard Time",
    "Myanmar Standard Time": "Myanmar Standard Time",
    "SE Asia Standard Time": "SE Asia Standard Time",
    "Altai Standard Time": "Altai Standard Time",
    "W. Mongolia Standard Time": "W. Mongolia Standard Time",
    "North Asia Standard Time": "Russia TZ 6 Standard Time",
    "N. Central Asia Standard Time": "Novosibirsk Standard Time",
    "Tomsk Standard Time": "Tomsk Standard Time",
    "China Standard Time": "China Standard Time",
    "North Asia East Standard Time": "Russia TZ 7 Standard Time",
    "Singapore Standard Time": "Malay Peninsula Standard Time",
    "W. Australia Standard Time": "W. Australia Standard Time",
    "Taipei Standard Time": "Taipei Standard Time",
    "Ulaanbaatar Standard Time": "Ulaanbaatar Standard Time",
    "Aus Central W. Standard Time": "Aus Central W. Standard Time",
    "Transbaikal Standard Time": "Transbaikal Standard Time",
    "Tokyo Standard Time": "Tokyo Standard Time",
    "North Korea Standard Time": "North Korea Standard Time",
    "Korea Standard Time": "Korea Standard Time",
    "Yakutsk Standard Time": "Russia TZ 8 Standard Time",
    "Cen. Australia Standard Time": "Cen. Australia Standard Time",
    "AUS Central Standard Time": "AUS Central Standard Time",
    "E. Australia Standard Time": "E. Australia Standard Time",
    "AUS Eastern Standard Time": "AUS Eastern Standard Time",
    "West Pacific Standard Time": "West Pacific Standard Time",
    "Tasmania Standard Time": "Tasmania Standard Time",
    "Vladivostok Standard Time": "Russia TZ 9 Standard Time",
    "Lord Howe Standard Time": "Lord Howe Standard Time",
    "Bougainville Standard Time": "Bougainville Standard Time",
    "Russia Time Zone 10": "Russia TZ 10 Standard Time",
    "Magadan Standard Time": "Magadan Standard Time",
    "Norfolk Standard Time": "Norfolk Standard Time",
    "Sakhalin Standard Time": "Sakhalin Standard Time",
    "Central Pacific Standard Time": "Central Pacific Standard Time",
    "Russia Time Zone 11": "Russia TZ 11 Standard Time",
    "New Zealand Standard Time": "New Zealand Standard Time",
    "UTC+12": "UTC+12",
    "Fiji Standard Time": "Fiji Standard Time",
    "Kamchatka Standard Time": "Kamchatka Standard Time",
    "Chatham Islands Standard Time": "Chatham Islands Standard Time",
    "UTC+13": "UTC+13",
    "Tonga Standard Time": "Tonga Standard Time",
    "Samoa Standard Time": "Samoa Standard Time",
    "Line Islands Standard Time": "Line Islands Standard Time"
};

export const IM_SERVICES: Record<string, string> = {
    "Google": "Google",
    "Teams": "Teams",
    "WhatsApp": "WhatsApp",
    "Telegram": "Telegram",
};

export const TAX_CLASSES: Record<string, string> = {
    "Individual/Sole Proprietor": "Individual/Sole Proprietor",
    "Corporation": "Corporation",
    "Partners/LLC/LLP": "Partners/LLC/LLP",
    "Other": "Other"
};

export const APPLICATION_TYPES: Record<string, string> = {
    "Web Traffic": "Web Traffic",
    "Call Traffic": "Call Traffic",
    "Both": "Both"
};
